### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by f-hicks** [Sulaiman-Gaskell/Password_Manager#1]
![Screenshot_20230118_111608_Termux.jpg](https://user-images.githubusercontent.com/84518177/213170141-7b1b7250-c808-46c8-b04c-9d6fc8e524f1.jpg)

**Comment by Sulaiman-Gaskell** [comment]
Will not fix not designed for mobile

**Comment by f-hicks** [comment]
May fix in future but sounds like effort

**Comment by f-hicks** [comment]
@Sulaiman-Gaskell heheheha

**Comment by Sulaiman-Gaskell** [comment]
Edit: will not fix

**Comment by f-hicks** [comment]
K thanks
